org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=512m -XX:+UseParallelGC
org.gradle.workers.max=2
org.gradle.parallel=false
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
